### PR TITLE
Add option to Center Align the Touch Bar displayed on screen

### PR DESCRIPTION
**Pull request by julianschiavo**
This pull request changes the following things:
- Add option for Left, Center, and Right Align in menubar, under On-Screen Touch Bar
- Change AppDelegate.m to add support for the new options

Current Bugs inside this Pull Request:
- ~~FIXED: Changing Center Align also changes the state of On-Screen Touch Bar~~
- Choosing a different option, e.g. Right Align, when one option, e.g. Center Align, is already ticked ticks both of them. Center Align takes priority followed by Left then Right when all 3 are ticked.

This pull request can be merged immediately, no changes required to original code.

@robbertkl

### CODE REVIEW

**Comment by robbertkl** [comment]
I'm sorry, I can't merge this. It won't even compile!

Also, it contains more commented out code, and way to much duplicated code: it should just be 1 setting which stores the fixed/alignment mode. Right now they are individual settings/toggles that can each be turned on and off.

You're already mentioning this bug yourself. Of course I won't be merging it while this bug is still present.. Having a priority in the handling is not a solution.

**Comment by julianschiavo** [comment]
I suck at Obj-C or any app coding and did this in a very basic manner. Obviously my code could be improved. I have now fixed the compile issue, I can't fix the individual toggle issue.

**Comment by julianschiavo** [comment]
And there were literally only a few separate commented out lines, fixed that too ( @robbertkl )

**Comment by robbertkl** [comment]
I know there were only a few, does that make it acceptable because they were "only a few"?

I'm sorry, I won't be merging this. I'll only merge PR's that add a feature or resolves a bug, not one that adds a bug. Please make sure feature addition PR's don't add new bugs.

**Comment by julianschiavo** [comment]
I have never heard of people having problems with *commented out* code.

This PR adds a new feature, making it one setting for all three is probably very very quick to do, but I can't do it. If you do not want to merge it, don't. I already have this feature, so I don't care. However, for all the people who keep requesting it, I feel bad for them, because most of them can't be bothered to compile code.

**Comment by wwdc17** [comment]
Awesome. Those people waiting for the feature will be incredibly happy now.

**Pull request closed without merging**
