### PR TITLE
Add option to Center Align touchbar

### PR DESCRIPTION
**Pull request by julianschiavo**
This pull request changes the following things:
- Add option for Left, Center, and Right Align in menubar, under On-Screen Touch Bar
- Change AppDelegate.m to add support for the new options

Current Bugs inside this Pull Request:
- ~~FIXED: Changing Center Align also changes the state of On-Screen Touch Bar~~
- Choosing a different option, e.g. Right Align, when one option, e.g. Center Align, is already ticked ticks both of them. Center Align takes priority followed by Left then Right when all 3 are ticked.

This pull request can be merged immediately.

### CODE REVIEW

**Comment by julianschiavo** [comment]
Hey @robbertkl I just added Left and Right align as well 😃... also updated the list of bugs and features.

**Comment by robbertkl** [comment]
Hi, thanks for your PR.

A few things:

* If you check the "Files changed" tab of this PR, you'll see that 99 (= almost all) files have been changed. Each file's permission has been changed from 644 to 755. Please make it so that only code changes are committed.
* The author of your git commit does not use the same e-mail address as your GitHub account, so your commit is not linked to your account. You might want to commit with a different e-mail to have it linked properly.
* The change to `self.movableByWindowBackground` in `TouchBarServer/TouchBarWindow.m` seems unrelated to / unnecessary for the added feature; please omit this change.

* The setting names are prefixed with the "mode" they are for, either `Screen` or `Remote`; the `CenterEnable` should therefor be called something like `ScreenAlignCenter`, since it applies to the on-screen Touch Bar. Actually, the main purpose of the setting is not aligning the Touch Bar, but rather fix it to specific screen position, so a better name would be something like `ScreenFixedCenter`.
* `centerornot` is not a good variable name; and it doesn't adhere to the camelcasing convention used in the rest of the code. Why is the variable even there? It seems to mirror the value of `_centerEnable` exactly; why not use `_centerEnable` instead?
* `changeCenterEnable:` contains a commented out line.
* `setCenterEnable:` toggles the state of the "On-Screen Touch Bar" submenu!
* In `toggleTouchBarWindow`, please do not use hardcoded `1095` value.
* In `toggleTouchBarWindow`, Please stick to the types you're given; no need to cast int's, don't use CGPointMake to make an NSPoint, etc.

Please review your changes carefully before committing and pushing.

**Comment by julianschiavo** [comment]
- >If you check the "Files changed" tab of this PR, you'll see that 99 (= almost all) files have been changed. Each file's permission has been changed from 644 to 755. Please make it so that only code changes are committed.
     - I don't know why that happened 🤔 
---
- >The author of your git commit does not use the same e-mail address as your GitHub account, so your commit is not linked to your account. You might want to commit with a different e-mail to have it linked properly.
     - I'll fix that now.
---
- >The change to self.movableByWindowBackground in TouchBarServer/TouchBarWindow.m seems unrelated to / unnecessary for the added feature; please omit this change.
     - That was me messing around 😛 
---
- >The setting names are prefixed with the "mode" they are for, either Screen or Remote; the CenterEnable should therefor be called something like ScreenAlignCenter, since it applies to the on-screen Touch Bar. Actually, the main purpose of the setting is not aligning the Touch Bar, but rather fix it to specific screen position, so a better name would be something like ScreenFixedCenter.
     - Lazy coding
---
- >centerornot is not a good variable name; and it doesn't adhere to the camelcasing convention used in the rest of the code. Why is the variable even there? It seems to mirror the value of _centerEnable exactly; why not use _centerEnable instead?
     - I didn't know _centerEnable was the same thing, I will try change and use that and retest.
---
- >changeCenterEnable: contains a commented out line.
     - Yes, because I write stuff and comment it out when it doesn't work. There I was trying to make them disable each other when one was ticked while others were already ticked.
---
- >setCenterEnable: toggles the state of the "On-Screen Touch Bar" submenu!
     - I don't understand this...
---
- >In toggleTouchBarWindow, please do not use hardcoded 1095 value.
     - This value is the width of the touch bar, it never changes and has to be set to that for it to work.
---
- >In toggleTouchBarWindow, Please stick to the types you're given; no need to cast int's, don't use CGPointMake to make an NSPoint, etc.
     - I did not write that code, it comes from https://github.com/bikkelbroeders/TouchBarDemoApp/issues/3
---
Anyways, I'll work on fixing these issues and resubmit the pull request.

**Comment by julianschiavo** [comment]
For those still checking this pull req by links, please head to https://github.com/bikkelbroeders/TouchBarDemoApp/pull/98 for the new one.

**Pull request closed without merging**
